#%RAML 1.0
title: Coding Garden Community App API
baseUri: https://app.coding.garden/api
version: v1
mediaType: application/vnd.api+json

/faq:
  get:
    responses: 
      200:
        body:
         example: |
            {
              "data": [{
                "type": "faq",
                "id": "1",
                "attributes": {
                  "question": "What break timer do you use?",
                  "answer": "It's called Time Out by Dejal. It is only available for Mac. For Windows, checkout Eye Leo. I have it setup for a 10 second micro break every 10 minutes and a 5 minute break every 60 minutes."
                }
              }, {
                "type": "faq",
                "id": "2",
                "attributes": {
                  "question": "Will the livestream be available as a video?",
                  "answer": "Yes! Every livestream is immediately available to watch after the stream is over. The URL is will be the same. Longer streams take time to process, but will show up on the Coding Garden videos page after a few hours."
                }
              }]
            }
  /{faqId}:
    uriParameters:
      faqId:
        type: integer
    get:
      responses:
        200:
          body:
            example: |
              {
                "data": {
                  "type": "faq",
                  "id": "2",
                  "attributes": {
                    "question": "Will the livestream be available as a video?",
                    "answer": "Yes! Every livestream is immediately available to watch after the stream is over. The URL is will be the same. Longer streams take time to process, but will show up on the Coding Garden videos page after a few hours."
                  }
                }
              }
        404:
          body:
            example: |
              {
                "errors": [{
                  "code": "e24",
                  "title": "Resource not found",
                  "detail": "There is no resource with type 'faq' and id '3'."
                }]
              }
/contributors:
  get:
    responses: 
      200:
        body:
          example: |
            {
              "data": [{
                "type": "contributor",
                "id": "sbibow",
                "attributes": {
                  "username": "sbibow",
                  "name": "Semjon Bibow",
                  "image": "https://avatars0.githubusercontent.com/u/5166002",
                  "countryCode": "DEU",
                  "active": true,
                  "joined": "2018-12-16"
                },
                "relationships": {
                  "contribution-area": {
                    "links": {
                      "self": "/contributors/sbibow/relationships/contribution-areas",
                      "related": "/contributors/sbibow/contribution-areas"
                    },
                    "data": [
                      { "type": "contribution-area", "id": "0" },
                      { "type": "contribution-area", "id": "4" },
                      { "type": "contribution-area", "id": "5" }
                    ]
                  }
                }
              }, {
                "type": "contributor",
                "id": "Sharpie360",
                "attributes": {
                  "username": "Sharpie360",
                  "name": "Sean Becker",
                  "image": "https://avatars0.githubusercontent.com/u/36274332",
                  "countryCode": "USA",
                  "active": true,
                  "joined": "2018-12-16"
                },
                "relationships": {
                  "contribution-area": {
                    "links": {
                      "self": "/contributors/Sharpie360/relationships/contribution-areas",
                      "related": "/contributors/Sharpie360/contribution-areas"
                    },
                    "data": [
                      { "type": "contribution-area", "id": "0" },
                      { "type": "contribution-area", "id": "1" },
                      { "type": "contribution-area", "id": "2" },
                      { "type": "contribution-area", "id": "3" },
                      { "type": "contribution-area", "id": "4" }
                    ]
                  }
                }
              }],
              "included": [
                { "type": "contribution-area", "id": "0", "attributes": { "name": "Planning" } },
                { "type": "contribution-area", "id": "1", "attributes": { "name": "Design" } },
                { "type": "contribution-area", "id": "2", "attributes": { "name": "Frontend" } },
                { "type": "contribution-area", "id": "3", "attributes": { "name": "Backend" } },
                { "type": "contribution-area", "id": "4", "attributes": { "name": "DevOps" } },
                { "type": "contribution-area", "id": "5", "attributes": { "name": "Testing" } }
              ]
            }
  /{userId}:
    get:
      responses: 
        200:
          body:
            example: |
              {
                "data": {
                  "type": "contributor",
                  "id": "sbibow",
                  "attributes": {
                    "username": "sbibow",
                    "name": "Semjon Bibow",
                    "image": "https://avatars0.githubusercontent.com/u/5166002",
                    "countryCode": "DEU",
                    "active": true,
                    "joined": "2018-12-16"
                  },
                  "relationships": {
                    "contribution-area": {
                      "links": {
                        "self": "/contributors/sbibow/relationships/contribution-areas",
                        "related": "/contributors/sbibow/contribution-areas"
                      },
                      "data": [
                        { "type": "contribution-area", "id": "0" },
                        { "type": "contribution-area", "id": "4" },
                        { "type": "contribution-area", "id": "5" }
                      ]
                    }
                  }
                },
                "included": [
                  { "type": "contribution-area", "id": "0", "attributes": { "name": "Planning" } },
                  { "type": "contribution-area", "id": "4", "attributes": { "name": "DevOps" } },
                  { "type": "contribution-area", "id": "5", "attributes": { "name": "Testing" } }
                ]
              }
    
    
    /contribution-areas:
      get:
        responses: 
          200:
            body:
              example: |
                {
                  "links": {
                    "self": "/contributors/sbibow/relationships/contribution-areas",
                    "related": "/contributors/sbibow/contribution-areas"
                  },
                  "data": [
                    { "type": "contribution-area", "id": "0" },
                    { "type": "contribution-area", "id": "4" },
                    { "type": "contribution-area", "id": "5" }
                  ]
                }    
    /relationships:
      /contribution-areas:
        get:
          responses: 
            200:
              body:
                example: |
                  {
                    "links": {
                      "self": "/contributors/sbibow/relationships/contribution-areas",
                      "related": "/contributors/sbibow/contribution-areas"
                    },
                    "data": [
                      { "type": "contribution-area", "id": "0" },
                      { "type": "contribution-area", "id": "4" },
                      { "type": "contribution-area", "id": "5" }
                    ]
                  }
/contribution-areas:
  get:
    responses: 
      200:
        body: 
          example: |
            {
              "data": [
                { "type": "contribution-area", "id": "0", "attributes": { "name": "Planning" } },
                { "type": "contribution-area", "id": "1", "attributes": { "name": "Design" } },
                { "type": "contribution-area", "id": "2", "attributes": { "name": "Frontend" } },
                { "type": "contribution-area", "id": "3", "attributes": { "name": "Backend" } },
                { "type": "contribution-area", "id": "4", "attributes": { "name": "DevOps" } },
                { "type": "contribution-area", "id": "5", "attributes": { "name": "Testing" } }
              ]
            }
/history:
  get: