openapi: 3.0.1
info:
  $ref: './Info.yaml#/Info'
servers:
  $ref: './Servers.yaml#/Servers'
tags:
  $ref: './Tags.yaml#/Tags'
paths:
  /contributors:
    get:
      $ref: './Paths/Contributors/Contributors.yaml#/AllContributors'

  /contributors/{id}:
    get:
      $ref: './Paths/Contributors/Contributors.yaml#/SingleContributor'

  /faqs:
    get:
      $ref: './Paths/FAQ/FAQ.yaml#/AllFAQs'
    post:
      $ref: './Paths/FAQ/FAQ.yaml#/AddFAQ'

  /faqs/{id}:
    get:
      $ref: './Paths/FAQ/FAQ.yaml#/SingleFAQ'
    delete:
      $ref: './Paths/FAQ/FAQ.yaml#/DeleteFAQ'

  /history:
    get:
      $ref: './Paths/History/History.yaml#/EntireHistory'

  /history/{id}:
    get:
      $ref: './Paths/History/History.yaml#/SingleMilestone'

  /videos:
    get:
      $ref: './Paths/Video/Video.yaml#/AllVideos'

  /videos/{id}:
    get:
      $ref: './Paths/Video/Video.yaml#/SingleVideo'

  /admin/seed:
    post:
      $ref: './Paths/Admin/Admin.yaml#/Seed'
