openapi: 3.0.1
info:
  $ref: './Info.yaml#/Info'
servers:
  $ref: './Servers.yaml#/Servers'
tags:
  $ref: './Tags.yaml#/Tags'
paths:
  /contributors:
    get:
      $ref: './Paths/Contributors.yaml#/AllContributors'
      
  /contributors/{id}:
    get:
      $ref: './Paths/Contributors.yaml#/SingleContributor'

  /faq:
    get:
      $ref: './Paths/FAQ.yaml#/AllFAQs'
    post:
      $ref: './Paths/FAQ.yaml#/AddFAQ'

  /faq/{id}:
    get:
      $ref: './Paths/FAQ.yaml#/SingleFAQ'
    delete:
      $ref: './Paths/FAQ.yaml#/DeleteFAQ'







