Error:
  type: object
  properties:
    message:
      type: string
    status:
      type: number
    stack:
      type: string

InternalServerError:
  description: 'Error: Internal Server Error'
  content:
    application/json:
      schema:
        type: object
        properties:
          message:
            type: string
          status:
            type: number
          stack:
            type: string
        example:
          message: Request to <URL> failed
          status: 500
          stack: 'FetchError: request to <URL> failed'

UnAuthorized:
  description: 'You are not authorized to perform this task.'
  content:
    application/json:
      schema:
        $ref: '#/Error'
      example:
        message: Un-Authorized
        status: 401
        stack: 'Error: Un-Authorized'

Contributor:
  type: object
  properties:
    "type":
      type: string
      example: contributor
    id:
      type: string
      example: w3cj
    attributes:
      type: object
      properties:
        username:
          type: string
          example: w3cj
        name:
          type: string
          example: CJ
        image:
          type: string
          example: 'https://avatars1.githubusercontent.com/u/14241866'
        countryCode:
          type: string
          example: USA
        active:
          type: boolean
          example: true
        joined:
          type: string
          example: '2018-12-16'
        teamIds:
          type: array
          items:
            type: number
          example:
            - 0
            - 1
            - 2
            - 3
            - 4

FAQ:
  type: object
  properties:
    "type":
      type: string
      example: faq
    id:
      type: string
      example: 5d526753bf8d2f24f4f12236
    attributes:
      required:
      - question
      - answer
      type: object
      properties:
        question:
          type: string
          example: What break timer do you use?
        answer:
          type: string
          example: It's called Time Out by Dejal. It is only available for Mac. For Windows, checkout Eye Leo. I have it setup for a 10 second micro break every 10 minutes and a 5 minute break every 60 minutes.
        createdAt:
          type: string
          example: 2019-08-13T07:31:31.879Z
        updatedAt:
          type: string
          example: 2019-08-13T07:31:31.879Z

Milestone:
  type: object
  required:
  - type
  properties:
    "type":
      type: string
      example: history
    id:
      type: string
      example: 5d53a0cfbb779e2988d67d10
    attributes:
      required:
      - name
      - date
      - description
      type: object
      properties:
        "type":
          type: string
          example: video
        name:
          type: string
          example: First video!
        videoID:
          type: string
          example: WYa47JkZH_U&t=552s
        date:
          type: string
          example: '2016-12-14T00:00:00.000Z'
        description:
          type: string
          example: The description of the video...
        url:
          type: string
          example: https://www.youtube.com/watch?v=WYa47JkZH_U&t=552s
        thumbnail:
          type: string
          example: https://i.ytimg.com/vi/WYa47JkZH_U/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAXBaYYlSuEcmhpAH712ajkjMcOxA
        createdAt:
          type: string
          example: '2019-08-14T05:49:03.844Z'
        updatedAt:
          type: string
          example: '2019-08-14T05:49:03.844Z'

